dataset: brats2021
seed: 3
size: 256 
source_domain: t1
target_domain: t2
data_path: /disk1/medical/brats2021/training
valid_path: /disk1/medical/brats2021/validation
batch_size: 8 
es_higher_limit: 80 
es_lower_limit: 50
gpu_id: 0
gpu_ids:
- '01234567'
num_workers: 8 
num_epochs: 50
work_dir: ./work_dir
save_log: true
debug: false
federated: false
data_num: 10000
lr: 0.001
#optimizer
beta1: 0.5
beta2: 0.999
#schduler
step_size: 30
gamma: 0.1
normalized_method: 'ortho'
#test_model
test_model: cyclegan
# diff
diff: l2
# train, validation, resume
train: False 
validate: False 
method: 'normal'
uniform_mode: ranking
#nirps_path
nirps_path: '/disk1/medical/nirps_dataset'
#noisy loss
noisy_loss: False
mu: 0.0
sigma: 0.05 
infer_range: all
latent_size: one_z