dataset: brats2021
noise_type: gaussian
seed: 3
size: 256 
a_mu: 0.0
a_sigma: 1.0
b_mu: 0.0
b_sigma: 1.0
source_domain: t1
target_domain: t2
data_path: /disk1/medical/brats2021/all
batch_size: 8 
es_higher_limit: 80 
es_lower_limit: 50
gpu_id: 0
gpu_ids:
- '01234567'
num_workers: 8 
num_epochs: 50
work_dir: ./work_dir
save_log: true
debug: false
federated: false
data_num: 10000
lr: 0.001
#optimizer
beta1: 0.5
beta2: 0.999
#schduler
step_size: 30
gamma: 0.1
#msl
msl_path: ./msl_stats
msl_stats: False 
msl_assigned: False
msl_assigned_value: 10
delta_diff: 10000
#loss
lambda_recon: 1.0
lambda_contrastive: 1.0
lambda_hf: 1.0
lambda_lf: 1.0
#test_model
test_model: cyclegan
# diff_method
diff_method: l1
# segmentation
segmentation: True
# train, validation, resume
train: False 
validation: False 
resume: False