dataset: brats2021
noise_type: gaussian
seed: 3
size: 256 
a_mu: 0.0
a_sigma: 1.0
b_mu: 0.0
b_sigma: 1.0
source_domain: t1
target_domain: t2
data_path: /disk1/medical/brats2021/training
valid_path: /disk1/medical/brats2021/validation
batch_size: 8 
es_higher_limit: 80 
es_lower_limit: 50
gpu_id: 0
gpu_ids:
- '01234567'
num_workers: 8 
num_epochs: 50
work_dir: ./work_dir
save_log: true
debug: false
federated: false
data_num: 10000
lr: 0.001
#optimizer
beta1: 0.5
beta2: 0.999
#schduler
step_size: 30
gamma: 0.1
#radius
radius_path: ./radius_stats
radius_stats: False 
radius_assigned: False
radius_assigned_value: 10
delta_diff: 10000
normalized_method: 'ortho'
#loss
lambda_recon: 1.0
lambda_contrastive: 1.0
lambda_hf: 1.0
lambda_lf: 1.0
#test_model
test_model: cyclegan
# diff_method
diff_method: l1
# segmentation
segmentation: True
# train, validation, resume
train: False 
validate: False 
resume: False
#visualization
vis_check: False
vis_method: 'np'
# load model
load_latest: False
assigned_epoch: 50
assigned_images: [['BraTS2021_00001', 'BraTS2021_00001', 70], 
                  ['BraTS2021_00013', 'BraTS2021_00013', 70],
                  ['BraTS2021_00438', 'BraTS2021_00438', 70],
                  ['BraTS2021_01668', 'BraTS2021_01668', 70],
                  ['BraTS2021_01712', 'BraTS2021_01712', 70],
                  ['BraTS2021_01756', 'BraTS2021_01756', 70],
                  ['BraTS2021_00585', 'BraTS2021_00585', 70],
                  ['BraTS2021_01679', 'BraTS2021_01679', 70],
                  ['BraTS2021_01763', 'BraTS2021_01763', 70]]