dataset: ixi
noise_type: kaid 
seed: 3
size: 256 
a_mu: 0.0
a_sigma: 1.0
b_mu: 0.0
b_sigma: 1.0
source_domain: pd
target_domain: t2
data_path: /disk1/medical/ixi
valid_path: /disk1/medical/ixi
batch_size: 8 
es_higher_limit: 80 
es_lower_limit: 50
gpu_id: 0
gpu_ids:
- '01234567'
num_workers: 8 
num_epochs: 50
work_dir: ./work_dir
save_log: true
debug: False 
federated: false
kaid_stats: false
data_num: 3000
lr: 0.0001
#optimizer
beta1: 0.5
beta2: 0.999
#schduler
step_size: 30
gamma: 0.1
#radius
radius_path: ./raidus_stats
radius_stats: False 
radius_assigned: False
radius_assigned_value: 10
delta_diff: 1000
normalized_method: 'ortho'
#loss
lambda_recon: 1.0
lambda_contrastive: 10.0
#test_model
test_model: cyclegan
# diff
diff: l2
# segmentation
segmentation: false
# train, validation, resume
train: False 
validate: False 
resume: False
#visualization
vis_check: False
vis_method: 'np'
# load model
load_latest: False
assigned_epoch: 50
# method
method: 'normal'
#nirps_path
nirps_path: '/disk1/medical/nirps_dataset'
#nirps start epcoh and end epoch
start_epoch: 1
end_epoch: 16
