federated: false
clients_data_weight:
- 1.0
# no differential privacy
diff_privacy: false
clip_bound: 1
sensitivity: 2
noise_multiplier: 1.07
# training
batch_size: 4 
gpu_id: 0
gpu_ids:
- '01234567'
lr: 0.0001
num_epoch: 30 
decay_epoch: 8 
seed: 3 
num_workers: 8
# test
direction: 'both'
# work file
work_dir: ./work_dir
save_log: true
save_img: false
debug: false 
# plot sample
plot_distribution: false
plot_num_sample: 2000
# save and load model
save_model: false
load_model: false
load_model_dir: None
# fid
fid: false
fid_dir: ./fid_stats
batch_size_inceptionV3: 8 
# optimizer
beta1: 0.5
beta2: 0.999
# identity loss
identity: true
lambda_identity: 10.0
# augmentation
auxiliary_rotation: false
auxiliary_translation: false
auxiliary_scaling: false
num_augmentation: 'one'


